-- 030_prohibited_items_seed.sql
--
-- Seed the prohibited_items table with the canonical UK → Kenya
-- restricted-goods catalogue. Mirrors the bundled client catalogue at
--   shared/src/commonMain/kotlin/com/thapsus/cargo/domain/prohibited/
--   ProhibitedItemsCatalog.kt
-- so the iOS / Android Pre-flight screen shows the same list regardless
-- of whether the client falls back to its bundled copy or fetches from
-- the server.
--
-- Sources of rules:
--   - Kenya Revenue Authority (KRA) import prohibitions + restrictions
--   - Kenya Bureau of Standards (KEBS) standardisation mark goods
--   - IATA Dangerous Goods Regulations 66th ed. (air-freight lane)
--   - Communications Authority of Kenya (CA)
--   - Pharmacy and Poisons Board (PPB)
--   - KEPHIS phytosanitary
--   - CITES
--   - UK export controls / open general licences
--
-- Run order: after 000_repair_phase4_tables.sql (which creates the
-- table) and 010_rls_lockdown.sql (which sets the SELECT policy for
-- authenticated users). Idempotent: uses ON CONFLICT DO NOTHING keyed
-- on (term, jurisdiction, language).

BEGIN;

-- One-time guard so re-running the seed doesn't double-write. The
-- target table inherits PK from the original schema; here we just
-- need a uniqueness anchor on (term, jurisdiction, language) for
-- ON CONFLICT to work.
ALTER TABLE public.prohibited_items
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS risk_level TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND indexname  = 'prohibited_items_term_jur_lang_uniq'
  ) THEN
    -- Lower-case the term in the index so 'Power bank' and 'power bank'
    -- don't both seed.
    CREATE UNIQUE INDEX prohibited_items_term_jur_lang_uniq
      ON public.prohibited_items (LOWER(term), jurisdiction, language);
  END IF;
END$$;

INSERT INTO public.prohibited_items
  (term, severity, jurisdiction, language, reason, category, risk_level)
VALUES
  -- ── Weapons & ammunition ───────────────────────────────────────────
  ('Firearms (rifles, handguns, shotguns)', 'prohibited', 'KE', 'en',
   'Cannot enter Kenya via cargo — only licensed dealers with KPS permits.',
   'Weapons & ammunition', 'critical'),
  ('Air rifles & air pistols', 'prohibited', 'KE', 'en',
   'Treated as firearms under Kenyan law; cargo import refused.',
   'Weapons & ammunition', 'critical'),
  ('Ammunition & gunpowder', 'prohibited', 'KE', 'en',
   'IATA dangerous-goods class 1; not accepted on this lane.',
   'Weapons & ammunition', 'critical'),
  ('Tasers & stun guns', 'prohibited', 'KE', 'en',
   'Banned under Kenyan firearms regulations.',
   'Weapons & ammunition', 'critical'),
  ('Crossbows', 'prohibited', 'KE', 'en',
   'Treated as offensive weapons under Kenyan law.',
   'Weapons & ammunition', 'critical'),
  ('Switchblades & flick knives', 'prohibited', 'KE', 'en',
   'Prohibited weapons under both UK and Kenyan law.',
   'Weapons & ammunition', 'critical'),
  ('Pepper spray & CS gas', 'prohibited', 'KE', 'en',
   'Restricted weapons; civilian import banned.',
   'Weapons & ammunition', 'critical'),
  ('Imitation / replica firearms', 'prohibited', 'KE', 'en',
   'Treated as real firearms by Kenyan customs.',
   'Weapons & ammunition', 'critical'),
  ('Gun parts (barrels, triggers, magazines)', 'prohibited', 'KE', 'en',
   'Same controls as a complete firearm.',
   'Weapons & ammunition', 'critical'),
  ('Body armour / bulletproof vests', 'prohibited', 'KE', 'en',
   'Restricted under Kenyan security regulations.',
   'Weapons & ammunition', 'critical'),

  -- ── Drugs & narcotics ─────────────────────────────────────────────
  ('Cannabis / marijuana (any form)', 'prohibited', 'KE', 'en',
   'Illegal in Kenya regardless of UK legality.',
   'Drugs & narcotics', 'critical'),
  ('CBD oil, CBD edibles, CBD vapes', 'prohibited', 'KE', 'en',
   'Treated as cannabis-derived; banned by PPB.',
   'Drugs & narcotics', 'critical'),
  ('Cocaine, heroin, methamphetamine', 'prohibited', 'KE', 'en',
   'Class A narcotics — criminal offence to import.',
   'Drugs & narcotics', 'critical'),
  ('Khat / miraa products', 'prohibited', 'KE', 'en',
   'Banned for export from the UK under the Misuse of Drugs Act.',
   'Drugs & narcotics', 'critical'),
  ('Kratom', 'prohibited', 'KE', 'en',
   'Controlled substance in Kenya.',
   'Drugs & narcotics', 'critical'),
  ('LSD, MDMA, psilocybin (magic mushrooms)', 'prohibited', 'KE', 'en',
   'Class A controlled substances.',
   'Drugs & narcotics', 'critical'),
  ('Anabolic steroids without prescription', 'prohibited', 'KE', 'en',
   'PPB-controlled; cannot import without doctor''s import permit.',
   'Drugs & narcotics', 'critical'),
  ('Drug paraphernalia (bongs, grinders, pipes)', 'prohibited', 'KE', 'en',
   'Prohibited under Kenyan narcotics law.',
   'Drugs & narcotics', 'critical'),
  ('Poppy seeds & opium-derivative tinctures', 'prohibited', 'KE', 'en',
   'Controlled under PPB; import banned.',
   'Drugs & narcotics', 'critical'),
  ('Cathinones / legal highs', 'prohibited', 'KE', 'en',
   'Treated as narcotics analogues.',
   'Drugs & narcotics', 'critical'),

  -- ── Currency, bullion & gemstones ─────────────────────────────────
  ('Banknotes & bulk cash (any currency)', 'prohibited', 'KE', 'en',
   'Cannot ship via courier; declare in person under POCAMLA.',
   'Currency, bullion & gemstones', 'critical'),
  ('Gold bars / bullion', 'prohibited', 'KE', 'en',
   'Requires KRA precious-metals dealer licence.',
   'Currency, bullion & gemstones', 'critical'),
  ('Silver bars / bullion', 'prohibited', 'KE', 'en',
   'Same precious-metals controls as gold.',
   'Currency, bullion & gemstones', 'critical'),
  ('Rough / uncut diamonds', 'prohibited', 'KE', 'en',
   'Kimberley Process Certificate required.',
   'Currency, bullion & gemstones', 'critical'),
  ('Bearer bonds & negotiable instruments', 'prohibited', 'KE', 'en',
   'Treated as cash under POCAMLA.',
   'Currency, bullion & gemstones', 'critical'),
  ('Cheques made out to bearer', 'prohibited', 'KE', 'en',
   'Same as bearer bonds.',
   'Currency, bullion & gemstones', 'critical'),
  ('Loose precious gemstones over £500', 'prohibited', 'KE', 'en',
   'Requires KRA precious-stones licence.',
   'Currency, bullion & gemstones', 'critical'),

  -- ── Live animals, ivory & wildlife products ───────────────────────
  ('Live animals (pets, birds, fish, reptiles)', 'prohibited', 'KE', 'en',
   'We don''t carry live cargo. Use a specialist pet shipper.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Ivory & ivory carvings', 'prohibited', 'KE', 'en',
   'CITES Appendix I — possession is a criminal offence.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Rhino horn', 'prohibited', 'KE', 'en',
   'CITES Appendix I — criminal offence.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Tortoise shells, coral, sea-shells', 'prohibited', 'KE', 'en',
   'Often CITES-listed; import without certificate is illegal.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Taxidermy / mounted heads', 'prohibited', 'KE', 'en',
   'Requires CITES permits not issued for commercial cargo.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Animal furs & exotic skins (snake, croc, leopard)', 'prohibited', 'KE', 'en',
   'CITES-controlled; UK export and Kenya import refused.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Raw hides & untanned skins', 'prohibited', 'KE', 'en',
   'Veterinary import permit required; not handled by this lane.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Live insects & arachnids', 'prohibited', 'KE', 'en',
   'KEPHIS phytosanitary refusal.',
   'Live animals, ivory & wildlife products', 'critical'),
  ('Eggs (poultry / wild bird)', 'prohibited', 'KE', 'en',
   'Veterinary import permit required; bird-flu risk.',
   'Live animals, ivory & wildlife products', 'critical'),

  -- ── Counterfeit & infringing goods ────────────────────────────────
  ('Counterfeit branded clothing & shoes', 'prohibited', 'KE', 'en',
   'Fake Nike, adidas, Louis Vuitton etc. seized at JKIA.',
   'Counterfeit & infringing goods', 'critical'),
  ('Counterfeit watches & jewellery', 'prohibited', 'KE', 'en',
   'Fake Rolex, Cartier etc. seized + destroyed.',
   'Counterfeit & infringing goods', 'critical'),
  ('Pirated DVDs, Blu-rays, software', 'prohibited', 'KE', 'en',
   'Copyright infringement; seized + destroyed.',
   'Counterfeit & infringing goods', 'critical'),
  ('Counterfeit electronics (fake AirPods, iPhones, chargers)', 'prohibited', 'KE', 'en',
   'Often unsafe and infringe trademarks.',
   'Counterfeit & infringing goods', 'critical'),
  ('Counterfeit medicines / generic Viagra etc.', 'prohibited', 'KE', 'en',
   'Counterfeit pharma is criminal and dangerous.',
   'Counterfeit & infringing goods', 'critical'),
  ('Counterfeit cosmetics & perfumes', 'prohibited', 'KE', 'en',
   'Often contain banned substances; seized.',
   'Counterfeit & infringing goods', 'critical'),
  ('Replica sports kit with fake club badges', 'prohibited', 'KE', 'en',
   'Trademark infringement.',
   'Counterfeit & infringing goods', 'critical'),

  -- ── Indecent material & extremist content ─────────────────────────
  ('Pornographic films, magazines, books', 'prohibited', 'KE', 'en',
   'Banned under Films, Stage Plays and Publications Act.',
   'Indecent material & extremist content', 'critical'),
  ('Child-protection-offence material', 'prohibited', 'KE', 'en',
   'Criminal offence in both jurisdictions; immediate referral.',
   'Indecent material & extremist content', 'critical'),
  ('Extremist / terrorist propaganda', 'prohibited', 'KE', 'en',
   'POTA Act — possession is an offence.',
   'Indecent material & extremist content', 'critical'),
  ('Hate-speech publications', 'prohibited', 'KE', 'en',
   'NCIC Act — incitement to ethnic hatred is criminal.',
   'Indecent material & extremist content', 'critical'),

  -- ── Human remains & body parts ────────────────────────────────────
  ('Cremated ashes', 'prohibited', 'KE', 'en',
   'Specialist undertaker repatriation only.',
   'Human remains & body parts', 'critical'),
  ('Human organs / tissue samples', 'prohibited', 'KE', 'en',
   'Medical-specialist freight only with HTA paperwork.',
   'Human remains & body parts', 'critical'),
  ('Human teeth, bones, hair samples (commercial qty)', 'prohibited', 'KE', 'en',
   'Cannot ship via standard cargo.',
   'Human remains & body parts', 'critical'),

  -- ── Explosives, radioactive & hazardous chemicals ─────────────────
  ('Fireworks & sparklers', 'prohibited', 'KE', 'en',
   'IATA class 1 — never accepted on belly-hold cargo.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Flares & distress signals', 'prohibited', 'KE', 'en',
   'Pyrotechnics — class 1 explosives.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Detonators & blasting caps', 'prohibited', 'KE', 'en',
   'Mining explosives — class 1.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Asbestos (any form)', 'prohibited', 'KE', 'en',
   'Banned under Kenyan environmental law.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Radioactive materials & isotopes', 'prohibited', 'KE', 'en',
   'Class 7 — Radiation Protection Board licence required.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Biological agents / clinical waste', 'prohibited', 'KE', 'en',
   'Specialist medical freight only.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Mercury thermometers & barometers', 'prohibited', 'KE', 'en',
   'Minamata Convention — phased out worldwide.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),
  ('Lead-acid / wet-cell batteries', 'prohibited', 'KE', 'en',
   'Class 8 corrosive; cannot fly without UN-spec packaging we don''t carry.',
   'Explosives, radioactive & hazardous chemicals', 'critical'),

  -- ── Lithium batteries & power banks ───────────────────────────────
  ('Loose lithium-ion batteries (any size)', 'dangerous_goods', 'KE', 'en',
   'Not accepted loose — must be installed in the device.',
   'Lithium batteries & power banks', 'high'),
  ('Power banks (any capacity)', 'dangerous_goods', 'KE', 'en',
   'Almost always refused by the airline — buy locally in Kenya.',
   'Lithium batteries & power banks', 'high'),
  ('Spare laptop batteries', 'dangerous_goods', 'KE', 'en',
   'Accepted only if installed in the laptop, not as a spare.',
   'Lithium batteries & power banks', 'high'),
  ('Spare phone batteries', 'dangerous_goods', 'KE', 'en',
   'Same rule: installed only, not loose.',
   'Lithium batteries & power banks', 'high'),
  ('E-bike / e-scooter batteries', 'dangerous_goods', 'KE', 'en',
   'Above 100 Wh — never accepted on passenger aircraft.',
   'Lithium batteries & power banks', 'high'),
  ('Drone batteries (separate)', 'dangerous_goods', 'KE', 'en',
   'Must remain installed in the drone; spares refused.',
   'Lithium batteries & power banks', 'high'),
  ('Vape / e-cigarette batteries (18650 cells)', 'dangerous_goods', 'KE', 'en',
   'Loose 18650 cells refused; cells in a device may pass.',
   'Lithium batteries & power banks', 'high'),

  -- ── Flammable liquids, aerosols & gases ───────────────────────────
  ('Perfumes & colognes (full-size, > 100 ml)', 'dangerous_goods', 'KE', 'en',
   'Most contain > 24% alcohol — class 3 flammable. Sample sizes only.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Nail polish & nail polish remover', 'dangerous_goods', 'KE', 'en',
   'Acetone-based — class 3 flammable.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Aerosol deodorants & hairsprays', 'dangerous_goods', 'KE', 'en',
   'Pressurised, flammable propellant.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Paints, varnishes, thinners', 'dangerous_goods', 'KE', 'en',
   'Flammable liquids — class 3.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Lighter fluid / butane refills', 'dangerous_goods', 'KE', 'en',
   'Class 2 flammable gas.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Lighters & matches', 'dangerous_goods', 'KE', 'en',
   'Refused unless empty (no fuel) and declared.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('CO2 cartridges (SodaStream, bike pumps)', 'dangerous_goods', 'KE', 'en',
   'Compressed gas — class 2.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Camping gas canisters', 'dangerous_goods', 'KE', 'en',
   'Propane / butane — class 2 flammable gas.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Pepper spray / mace', 'dangerous_goods', 'KE', 'en',
   'Pressurised + irritant; also banned by Kenyan law.',
   'Flammable liquids, aerosols & gases', 'high'),
  ('Tear-gas canisters', 'dangerous_goods', 'KE', 'en',
   'Class 2 + Kenyan firearms/weapons law.',
   'Flammable liquids, aerosols & gases', 'high'),

  -- ── Corrosives, oxidisers & toxic chemicals ───────────────────────
  ('Bleach (concentrated)', 'dangerous_goods', 'KE', 'en',
   'Class 8 corrosive.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Drain cleaner / oven cleaner', 'dangerous_goods', 'KE', 'en',
   'Highly corrosive — class 8.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Hydrogen peroxide (> 8%)', 'dangerous_goods', 'KE', 'en',
   'Class 5.1 oxidiser.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Pool chlorine tablets', 'dangerous_goods', 'KE', 'en',
   'Class 5.1 oxidiser.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Pesticides & insecticides', 'dangerous_goods', 'KE', 'en',
   'Class 6.1 toxic + KEPHIS permit.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Weedkillers & herbicides', 'dangerous_goods', 'KE', 'en',
   'Class 6.1 toxic + KEPHIS permit.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),
  ('Acids (sulphuric, hydrochloric, nitric)', 'dangerous_goods', 'KE', 'en',
   'Class 8 — never accepted.',
   'Corrosives, oxidisers & toxic chemicals', 'high'),

  -- ── Magnets, magnetised devices & high-EMF gear ───────────────────
  ('Rare-earth / neodymium magnets (N52, N50, etc.)', 'dangerous_goods', 'KE', 'en',
   'Magnetic field above IATA''s 0.418 A/m at 4.5 m limit — refused.',
   'Magnets, magnetised devices & high-EMF gear', 'high'),
  ('Magnetic toys (e.g. Buckyballs, Geomag)', 'dangerous_goods', 'KE', 'en',
   'Refused above neodymium threshold; small ferrite magnets OK.',
   'Magnets, magnetised devices & high-EMF gear', 'high'),
  ('Large speaker drivers / subwoofer magnets', 'dangerous_goods', 'KE', 'en',
   'Often above IATA threshold — packaged shielded only.',
   'Magnets, magnetised devices & high-EMF gear', 'high'),

  -- ── Pharmaceuticals & medical devices ─────────────────────────────
  ('Prescription medicines (personal supply)', 'restricted', 'KE', 'en',
   'Bring your prescription scan — up to 3 months supply.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Insulin, EpiPens & injectables', 'restricted', 'KE', 'en',
   'Personal-use allowed with prescription; refrigeration risk.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Vitamins & supplements (commercial qty)', 'restricted', 'KE', 'en',
   'PPB permit required above personal-use quantities.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Hearing aids & batteries', 'restricted', 'KE', 'en',
   'Personal device — declare on commercial invoice.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Glucose meters, blood-pressure monitors', 'restricted', 'KE', 'en',
   'Declare as medical device; KEBS standardisation mark may apply.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Contact lenses & solution', 'restricted', 'KE', 'en',
   'Personal supply OK; bulk needs PPB permit.',
   'Pharmaceuticals & medical devices', 'medium'),
  ('Surgical instruments', 'restricted', 'KE', 'en',
   'Importer permit required.',
   'Pharmaceuticals & medical devices', 'medium'),

  -- ── Food, beverages & alcohol ─────────────────────────────────────
  ('Wine & spirits (over 1 L)', 'restricted', 'KE', 'en',
   'High excise duty + wholesaler permit for > 1 L per consignee.',
   'Food, beverages & alcohol', 'medium'),
  ('Beer', 'restricted', 'KE', 'en',
   'Glass-bottle breakage risk; commercial qty needs permit.',
   'Food, beverages & alcohol', 'medium'),
  ('Fresh fruit & vegetables', 'restricted', 'KE', 'en',
   'KEPHIS phytosanitary certificate required.',
   'Food, beverages & alcohol', 'medium'),
  ('Raw meat & poultry', 'restricted', 'KE', 'en',
   'Veterinary import permit needed; cold-chain not offered.',
   'Food, beverages & alcohol', 'medium'),
  ('Cheese & dairy', 'restricted', 'KE', 'en',
   'Veterinary permit + cold chain — limited acceptance.',
   'Food, beverages & alcohol', 'medium'),
  ('Honey', 'restricted', 'KE', 'en',
   'Veterinary permit required.',
   'Food, beverages & alcohol', 'medium'),
  ('Baby formula (commercial qty)', 'restricted', 'KE', 'en',
   'KEBS approval; personal qty up to 6 tubs typically passes.',
   'Food, beverages & alcohol', 'medium'),
  ('Protein powders & sports supplements', 'restricted', 'KE', 'en',
   'KEBS mark required for retail labels; personal use OK.',
   'Food, beverages & alcohol', 'medium'),

  -- ── Cosmetics, skincare & toiletries ──────────────────────────────
  ('Skin-lightening creams (hydroquinone > 2%)', 'prohibited', 'KE', 'en',
   'PPB-banned; many UK retail creams exceed the Kenyan limit.',
   'Cosmetics, skincare & toiletries', 'medium'),
  ('Cosmetics (commercial quantity)', 'restricted', 'KE', 'en',
   'KEBS PVoC + standardisation mark.',
   'Cosmetics, skincare & toiletries', 'medium'),
  ('Sunscreens above SPF 50', 'restricted', 'KE', 'en',
   'KEBS approval for retail labelling.',
   'Cosmetics, skincare & toiletries', 'medium'),
  ('Hair-relaxer / chemical perm kits', 'restricted', 'KE', 'en',
   'Class 8 corrosive ingredient — check packaging.',
   'Cosmetics, skincare & toiletries', 'medium'),

  -- ── Telecoms, radio & SIM equipment ───────────────────────────────
  ('Mobile phones (new, with original IMEI)', 'restricted', 'KE', 'en',
   'OK to ship; register the IMEI with your local network within 60 days.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('Mobile phones (refurbished without box)', 'restricted', 'KE', 'en',
   'Higher chance of customs valuation dispute.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('4G / 5G modems & MiFi routers', 'restricted', 'KE', 'en',
   'CA type-approval check on entry.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('Walkie-talkies / two-way radios', 'restricted', 'KE', 'en',
   'CA licence required to operate.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('CB / amateur radio gear', 'restricted', 'KE', 'en',
   'Operator licence required.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('GPS trackers / vehicle telematics', 'restricted', 'KE', 'en',
   'CA registration for the SIM module.',
   'Telecoms, radio & SIM equipment', 'medium'),
  ('Signal boosters / repeaters', 'prohibited', 'KE', 'en',
   'Unlicensed boosters are banned by the CA.',
   'Telecoms, radio & SIM equipment', 'medium'),

  -- ── Drones, UAVs & RC aircraft ────────────────────────────────────
  ('Camera drones (DJI Mini, Mavic, Phantom)', 'restricted', 'KE', 'en',
   'KCAA registration required; battery must stay installed.',
   'Drones, UAVs & RC aircraft', 'high'),
  ('Racing / FPV drones', 'restricted', 'KE', 'en',
   'KCAA registration; some military-radio-band models refused.',
   'Drones, UAVs & RC aircraft', 'high'),
  ('RC planes & helicopters with combustion engines', 'restricted', 'KE', 'en',
   'No fuel residue allowed in the engine.',
   'Drones, UAVs & RC aircraft', 'high'),
  ('Drones with thermal-imaging payload', 'prohibited', 'KE', 'en',
   'Dual-use export control under UK strategic goods.',
   'Drones, UAVs & RC aircraft', 'high'),

  -- ── Tobacco, vapes & nicotine ─────────────────────────────────────
  ('Cigarettes (over 200)', 'restricted', 'KE', 'en',
   'Above personal allowance → excise duty + permit.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Cigars & pipe tobacco', 'restricted', 'KE', 'en',
   'Same excise + permit rule.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Vape devices (with battery installed)', 'restricted', 'KE', 'en',
   'Battery installed + powered off — DG declaration may be needed.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Vape devices (loose batteries)', 'dangerous_goods', 'KE', 'en',
   'Loose 18650 cells refused under IATA.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Vape juice / e-liquid', 'restricted', 'KE', 'en',
   'Contains nicotine — KRA excise + KEBS approval.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Nicotine pouches (Snus, Zyn, etc.)', 'restricted', 'KE', 'en',
   'Tobacco-product treatment under Kenyan law.',
   'Tobacco, vapes & nicotine', 'medium'),
  ('Shisha tobacco & molasses', 'prohibited', 'KE', 'en',
   'Banned for public consumption in Kenya since 2017.',
   'Tobacco, vapes & nicotine', 'medium'),

  -- ── Plants, seeds & soil ──────────────────────────────────────────
  ('Live plants & cuttings', 'restricted', 'KE', 'en',
   'Phytosanitary certificate from origin country required.',
   'Plants, seeds & soil', 'medium'),
  ('Seeds (any kind)', 'restricted', 'KE', 'en',
   'Phytosanitary certificate + KEPHIS import permit.',
   'Plants, seeds & soil', 'medium'),
  ('Soil & growing media', 'prohibited', 'KE', 'en',
   'Pest / disease vector — banned import.',
   'Plants, seeds & soil', 'medium'),
  ('Cut flowers', 'restricted', 'KE', 'en',
   'Phytosanitary certificate.',
   'Plants, seeds & soil', 'medium'),

  -- ── Used clothing & textiles (mitumba) ────────────────────────────
  ('Bulk used clothing (commercial qty)', 'restricted', 'KE', 'en',
   'Needs mitumba importer permit.',
   'Used clothing & textiles (mitumba)', 'medium'),
  ('Used shoes (bulk)', 'restricted', 'KE', 'en',
   'Same mitumba regime.',
   'Used clothing & textiles (mitumba)', 'medium'),
  ('Used bed linen, towels', 'restricted', 'KE', 'en',
   'Personal qty fine; commercial flagged.',
   'Used clothing & textiles (mitumba)', 'medium'),

  -- ── Items needing trader paperwork ────────────────────────────────
  ('Building / construction materials', 'restricted', 'KE', 'en',
   'Commercial valuation; KEBS standardisation for many lines.',
   'Items needing trader paperwork', 'medium'),
  ('Spare car parts (commercial)', 'restricted', 'KE', 'en',
   'KEBS + KRA inspector valuation.',
   'Items needing trader paperwork', 'medium'),
  ('Used car tyres', 'prohibited', 'KE', 'en',
   'Banned import since 2018 for safety reasons.',
   'Items needing trader paperwork', 'medium'),
  ('Refrigerators / air conditioners (used)', 'restricted', 'KE', 'en',
   'Older units with banned refrigerants (R12, R22) refused.',
   'Items needing trader paperwork', 'medium'),
  ('Solar panels (commercial qty)', 'restricted', 'KE', 'en',
   'EPRA / KEBS approval required for resale.',
   'Items needing trader paperwork', 'medium'),

  -- ── Adult products & lifestyle ────────────────────────────────────
  ('Sex toys (discreet, personal)', 'restricted', 'KE', 'en',
   'Plain packaging only; some shipments are spot-rejected.',
   'Adult products & lifestyle', 'medium'),
  ('Adult lingerie', 'restricted', 'KE', 'en',
   'No restriction unless packaging is sexually explicit.',
   'Adult products & lifestyle', 'medium'),
  ('Lubricants & intimate-care products', 'restricted', 'KE', 'en',
   'Cosmetic / pharmaceutical labelling controls.',
   'Adult products & lifestyle', 'medium')
ON CONFLICT (LOWER(term), jurisdiction, language) DO NOTHING;

COMMIT;
